#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean Test-extendedRealizability
wclean extendedRealizability

# ----------------------------------------------------------------- end-of-file
